import os
from dotenv import load_dotenv

load_dotenv()

BOT_NAME = "BestSocialBot"
BOT_TOKEN = os.getenv("MAIN_BOT_TOKEN")
CHANNEL_ID = int(os.getenv("CHANNEL_ID", "-1002160822750"))
CHANNEL_URL = os.getenv("CHANNEL_URL", "https://t.me/avto_avia_club")
ADMIN_ID = int(os.getenv("ADMIN_ID", "0"))
SHOWCASE_INTERVAL = int(os.getenv("SHOWCASE_INTERVAL", "21600"))
CREDENTIALS_FILE = os.getenv("CREDENTIALS_FILE", "credentials.json")
SHOWCASE_IMAGE_URL = os.getenv("SHOWCASE_IMAGE_URL", "https://i.postimg.cc/d3DLXMwT/social.jpg")

TELETHON_API_ID = int(os.getenv("TELETHON_API_ID", "0"))
TELETHON_API_HASH = os.getenv("TELETHON_API_HASH", "")
TELETHON_PHONE_NUMBER = os.getenv("TELETHON_PHONE_NUMBER", "")

MAIN_SURVEY_SHEET_URL = os.getenv("MAIN_GOOGLE_SHEET", "")
BESTHOME_SURVEY_SHEET_URL = os.getenv("BESTHOME_SURVEY_SHEET_URL", "")
AUTO_SURVEY_SHEET_URL = os.getenv("AUTO_SURVEY_SHEET_URL", "")
WOND_SURVEY_SHEET_URL = MAIN_SURVEY_SHEET_URL
INVESTMENTS_SHEET_URL = os.getenv("INVESTMENTS_SHEET_URL", "")

KNOWN_BOT_SHEETS = {
    "InvestmentsBot": INVESTMENTS_SHEET_URL,
}

PARSING_USERS_GOOGLE_SHEET_URL = os.getenv("PARSING_USERS_GOOGLE_SHEET_URL", "")

PLANS_REPORTS_SHEET_URL = MAIN_SURVEY_SHEET_URL
MAILING_ADDRESSES_SHEET_URL = MAIN_SURVEY_SHEET_URL
COMMON_EXPORT_SHEET_URL = MAIN_SURVEY_SHEET_URL
AUTO_PRODUCTS_SHEET_URL = MAIN_SURVEY_SHEET_URL
AUTO_SERVICES_SHEET_URL = MAIN_SURVEY_SHEET_URL
AUTO_ORDERS_SHEET_URL = MAIN_SURVEY_SHEET_URL
STATISTICS_SHEET_URL = MAIN_SURVEY_SHEET_URL
CUMULATIVE_STATS_SHEET_URL = MAIN_SURVEY_SHEET_URL
INVITE_EXPORT_SHEET_URL = MAIN_SURVEY_SHEET_URL
AUTO_CATEGORIES_SHEET_URL = MAIN_SURVEY_SHEET_URL
USER_BONUSES_SHEET_URL = MAIN_SURVEY_SHEET_URL
REVIEWS_SHEET_URL = MAIN_SURVEY_SHEET_URL
INVESTORS_SHEET_URL = MAIN_SURVEY_SHEET_URL
PARTNERS_SHEET_URL = MAIN_SURVEY_SHEET_URL
SHEET_ORDERS = AUTO_ORDERS_SHEET_URL
HOUSING_CATEGORIES = [
    "Односемейный жилой дом",
    "Таунхаус",
    "Таунхаус и Дуплекс",
    "Кондоминиум",
    "Квартира",
    "Комната"
]
